In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import os
from matplotlib import pyplot as plt

In [4]:
missing_value = ["N/a", "na", np.nan]
df = pd.read_csv("./Dataset/tweets_24_tendencias_raw.csv", low_memory=False, na_values=missing_value)

In [8]:
df.head()

,Unnamed: 0.1,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,reply_to,retweet_date,translate,trans_src,trans_dest,trend,Unnamed: 0,hours,day,month
0,0,1.231919e+18,1.231919e+18,2020-02-24 13:28:15 Romance Standard Time,2020-02-24,13:28:15,100.0,5.487197e+08,djurekbl,Marko Djurek,...,[],NaN,NaN,NaN,NaN,#AtletiVillareal,NaN,NaN,NaN,NaN
1,1,1.231871e+18,1.231871e+18,2020-02-24 10:18:31 Romance Standard Time,2020-02-24,10:18:31,100.0,7.882786e+17,indioscaledonia,Indios de Caledonia,...,[],NaN,NaN,NaN,NaN,#AtletiVillareal,NaN,NaN,NaN,NaN
2,2,1.232062e+18,1.162480e+18,2020-02-24 22:56:17 Romance Standard Time,2020-02-24,22:56:17,100.0,8.602287e+17,dataafaok,Data Afa (desde üè°),...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
3,3,1.232044e+18,1.232044e+18,2020-02-24 21:46:20 Romance Standard Time,2020-02-24,21:46:20,100.0,8.434539e+17,mas_que_pelotas,M√°s Que Pelotas¬ÆÔ∏è,...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
4,4,1.232044e+18,1.232044e+18,2020-02-24 21:45:00 Romance Standard Time,2020-02-24,21:45:00,100.0,8.434539e+17,mas_que_pelotas,M√°s Que Pelotas¬ÆÔ∏è,...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN

In [5]:
df.isnull().sum()

Unnamed: 0.1             0
id                  901218
conversation_id     901218
created_at          901218
date                     0
time                     0
timezone            901218
user_id             901218
username                 0
name                901260
place              1616032
tweet                  219
language            901218
mentions            805896
urls                     0
photos                   0
replies_count            0
retweets_count           0
likes_count              0
hashtags            773328
cashtags            901218
link                901218
retweet                  0
quote_url          1564275
video                    0
thumbnail          1477745
near               1618956
geo                1618956
source             1618956
user_rt_id         1618956
user_rt            1618956
retweet_id         1618956
reply_to            522006
retweet_date       1618956
translate          1618956
trans_src          1618956
trans_dest         1618956
trend               901218
Unnamed: 0          417523
hours               717738
day                 717738
month               717738
dtype: int64

In [6]:
df

,Unnamed: 0.1,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,reply_to,retweet_date,translate,trans_src,trans_dest,trend,Unnamed: 0,hours,day,month
0,0,1.231919e+18,1.231919e+18,2020-02-24 13:28:15 Romance Standard Time,2020-02-24,13:28:15,100.0,5.487197e+08,djurekbl,Marko Djurek,...,[],NaN,NaN,NaN,NaN,#AtletiVillareal,NaN,NaN,NaN,NaN
1,1,1.231871e+18,1.231871e+18,2020-02-24 10:18:31 Romance Standard Time,2020-02-24,10:18:31,100.0,7.882786e+17,indioscaledonia,Indios de Caledonia,...,[],NaN,NaN,NaN,NaN,#AtletiVillareal,NaN,NaN,NaN,NaN
2,2,1.232062e+18,1.162480e+18,2020-02-24 22:56:17 Romance Standard Time,2020-02-24,22:56:17,100.0,8.602287e+17,dataafaok,Data Afa (desde üè°),...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
3,3,1.232044e+18,1.232044e+18,2020-02-24 21:46:20 Romance Standard Time,2020-02-24,21:46:20,100.0,8.434539e+17,mas_que_pelotas,M√°s Que Pelotas¬ÆÔ∏è,...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
4,4,1.232044e+18,1.232044e+18,2020-02-24 21:45:00 Romance Standard Time,2020-02-24,21:45:00,100.0,8.434539e+17,mas_que_pelotas,M√°s Que Pelotas¬ÆÔ∏è,...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1618951,300210,1.231731e+18,1.231731e+18,2020-02-24 01:00:12 Hora est√°ndar romance,2020-02-24,01:00:12,100.0,1.070024e+09,valemagalii,Valeria,...,[],NaN,NaN,NaN,NaN,Volver,23354.0,NaN,NaN,NaN
1618952,300211,1.231730e+18,1.231730e+18,2020-02-24 01:00:08 Hora est√°ndar romance,2020-02-24,01:00:08,100.0,2.212802e+09,puntsiapart,Marta RC,...,[],NaN,NaN,NaN,NaN,Volver,23355.0,NaN,NaN,NaN
1618953,300212,1.231730e+18,1.231730e+18,2020-02-24 01:00:04 Hora est√°ndar romance,2020-02-24,01:00:04,100.0,1.090190e+18,botpoemas,Poemas,...,[],NaN,NaN,NaN,NaN,Volver,23356.0,NaN,NaN,NaN
1618954,300213,1.231730e+18,1.231610e+18,2020-02-24 01:00:02 Hora est√°ndar romance,2020-02-24,01:00:02,100.0,4.654166e+07,danir0cha,~ Daniela,...,[],NaN,NaN,NaN,NaN,Volver,23357.0,NaN,NaN,NaN
1618955,300214,1.231730e+18,1.231730e+18,2020-02-24 01:00:00 Hora est√°ndar romance,2020-02-24,01:00:00,100.0,5.738516e+08,canal_13c,Canal 13C,...,[],NaN,NaN,NaN,NaN,Volver,23358.0,NaN,NaN,NaN

In [7]:
df.dropna(how="all")
# df.dropna()

,Unnamed: 0.1,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,reply_to,retweet_date,translate,trans_src,trans_dest,trend,Unnamed: 0,hours,day,month
0,0,1.231919e+18,1.231919e+18,2020-02-24 13:28:15 Romance Standard Time,2020-02-24,13:28:15,100.0,5.487197e+08,djurekbl,Marko Djurek,...,[],NaN,NaN,NaN,NaN,#AtletiVillareal,NaN,NaN,NaN,NaN
1,1,1.231871e+18,1.231871e+18,2020-02-24 10:18:31 Romance Standard Time,2020-02-24,10:18:31,100.0,7.882786e+17,indioscaledonia,Indios de Caledonia,...,[],NaN,NaN,NaN,NaN,#AtletiVillareal,NaN,NaN,NaN,NaN
2,2,1.232062e+18,1.162480e+18,2020-02-24 22:56:17 Romance Standard Time,2020-02-24,22:56:17,100.0,8.602287e+17,dataafaok,Data Afa (desde üè°),...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
3,3,1.232044e+18,1.232044e+18,2020-02-24 21:46:20 Romance Standard Time,2020-02-24,21:46:20,100.0,8.434539e+17,mas_que_pelotas,M√°s Que Pelotas¬ÆÔ∏è,...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
4,4,1.232044e+18,1.232044e+18,2020-02-24 21:45:00 Romance Standard Time,2020-02-24,21:45:00,100.0,8.434539e+17,mas_que_pelotas,M√°s Que Pelotas¬ÆÔ∏è,...,[],NaN,NaN,NaN,NaN,#AtletiVillarreal,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1618951,300210,1.231731e+18,1.231731e+18,2020-02-24 01:00:12 Hora est√°ndar romance,2020-02-24,01:00:12,100.0,1.070024e+09,valemagalii,Valeria,...,[],NaN,NaN,NaN,NaN,Volver,23354.0,NaN,NaN,NaN
1618952,300211,1.231730e+18,1.231730e+18,2020-02-24 01:00:08 Hora est√°ndar romance,2020-02-24,01:00:08,100.0,2.212802e+09,puntsiapart,Marta RC,...,[],NaN,NaN,NaN,NaN,Volver,23355.0,NaN,NaN,NaN
1618953,300212,1.231730e+18,1.231730e+18,2020-02-24 01:00:04 Hora est√°ndar romance,2020-02-24,01:00:04,100.0,1.090190e+18,botpoemas,Poemas,...,[],NaN,NaN,NaN,NaN,Volver,23356.0,NaN,NaN,NaN
1618954,300213,1.231730e+18,1.231610e+18,2020-02-24 01:00:02 Hora est√°ndar romance,2020-02-24,01:00:02,100.0,4.654166e+07,danir0cha,~ Daniela,...,[],NaN,NaN,NaN,NaN,Volver,23357.0,NaN,NaN,NaN
1618955,300214,1.231730e+18,1.231730e+18,2020-02-24 01:00:00 Hora est√°ndar romance,2020-02-24,01:00:00,100.0,5.738516e+08,canal_13c,Canal 13C,...,[],NaN,NaN,NaN,NaN,Volver,23358.0,NaN,NaN,NaN